#!/usr/bin/env python3
"""Build the exactodds npm SDK from the gated .exactodds rule sources.

For each games/*.exactodds: emit the JS seat, extract the rule functions
(dropping the runtime helpers and the audited say()/main demo),
and write sdk/js/rules/<slug>.js as a clean CommonJS module.
Also generates sdk/js/index.js, runtime.js, and test/run.js, which
replays every audited say() call from the rule source against the
built modules and diffs the golden fixtures.

Set EXACTODDS_ROOT to the repo checkout (defaults to the repo layout
relative to this script).
"""
import json, os, re, subprocess, sys

ROOT = os.environ.get("EXACTODDS_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GAMES = os.path.join(ROOT, "games")
SDK = os.path.join(ROOT, "sdk", "js")
RULES = os.path.join(SDK, "rules")
CUNI = os.path.expanduser("~/workspace/cuni-langs/target/debug/cuni")
HELPERS = {"say", "range", "abs", "min", "max", "_eo_slice", "_eo_div"}
# The emit backend still names its helpers _cuni_slice/_cuni_div/CuNiError;
# RENAME_MAP rebrands them in generated output (public surfaces carry
# no CuNi branding).
RENAME_MAP = {"_cuni_slice": "_eo_slice", "_cuni_div": "_eo_div",
              "CuNiError": "ExactOddsError",
              "CuNi JS seat runtime": "ExactOdds JS runtime",
              "Generated by the CuNi toy JavaScript backend.": "Generated by the ExactOdds JavaScript backend.",
              "CuNi's explicit failure-signaling statement.": "the explicit failure-signaling statement."}

SLUGS = [
    "provably-fair-dice", "provably-fair-coin-flip", "provably-fair-roulette",
    "provably-fair-crash", "casino-bonus-wagering", "casino-poker-rake",
    "casino-sportsbook-settlement", "casino-affiliate-revshare",
    "casino-responsible-limits", "casino-slots-payline",
    "casino-progressive-jackpot", "casino-tourney-points", "casino-cashback",
    "casino-aml-structuring", "casino-referral-bonus", "casino-comp-points",
    "casino-rtp-audit", "casino-raffle-draw", "casino-baccarat-settle",
]

os.makedirs(RULES, exist_ok=True)
os.makedirs(os.path.join(SDK, "test"), exist_ok=True)

# fixture files predate the provably-fair-* renames for the original games
FIXTURE_NAME = {
    "provably-fair-dice": "dice",
    "provably-fair-coin-flip": "coin-flip",
    "provably-fair-roulette": "roulette",
    "provably-fair-crash": "crash",
}

FUNC_RE = re.compile(r"^function (\w+)\(([^)]*)\) \{(.*?)^\}$", re.M | re.S)
DEF_RE = re.compile(r"^def (\w+)\(([^)]*)\) -> (\w+) do", re.M)
SAY_RE = re.compile(r"^say\((.*)\)$", re.M)

all_funcs = {}   # fn name -> slug (collision check)
index_entries = []
test_cases = []  # (slug, [say exprs], fixture lines)

for slug in SLUGS:
    src_path = os.path.join(GAMES, slug + ".exactodds")
    src = open(src_path).read()
    defs = DEF_RE.findall(src)
    says = SAY_RE.findall(src)
    fname = FIXTURE_NAME.get(slug, slug)
    fixture = open(os.path.join(ROOT, "gate", "fixtures", fname + ".stdout")).read().splitlines()
    assert len(says) == len(fixture), f"{slug}: say/fixture count mismatch"

    out_js = os.path.join("/tmp", slug + ".emit.js")
    subprocess.run([CUNI, src_path, "--emit-js", out_js],
                   check=True, capture_output=True)
    text = open(out_js).read()
    for old, new in RENAME_MAP.items():
        text = text.replace(old, new)

    rule_funcs = []
    for name, params, body in FUNC_RE.findall(text):
        if name in HELPERS or name == "main":
            continue
        rule_funcs.append((name, params, body))
        if name in all_funcs:
            print(f"COLLISION: {name} in {all_funcs[name]} and {slug}", file=sys.stderr)
            sys.exit(1)
        all_funcs[name] = slug

    # runtime.js = everything before the first rule function
    first_rule = f"function {rule_funcs[0][0]}("
    runtime_src = text[:text.index(first_rule)]

    lines = [f"// Generated from games/{slug}.exactodds — do not hand-edit.",
             "const { say, range, abs, min, max, _eo_slice, _eo_div, ExactOddsError } = require('../runtime.js');",
             ""]
    for name, params, body in rule_funcs:
        lines.append(f"function {name}({params}) {{{body}}}")
        lines.append("")
    lines.append("module.exports = { " + ", ".join(n for n, _, _ in rule_funcs) + " };")
    open(os.path.join(RULES, slug + ".js"), "w").write("\n".join(lines) + "\n")

    index_entries.append((slug, [n for n, _, _ in rule_funcs]))
    test_cases.append((slug, says, fixture))

rt = runtime_src.replace(
    "// Generated by the ExactOdds JavaScript backend. Do not hand-edit.\n\n", "")
open(os.path.join(SDK, "runtime.js"), "w").write(
    "// ExactOdds JS runtime — shared by all rule modules. Do not hand-edit.\n"
    + rt
    + "\nmodule.exports = { say, range, abs, min, max, _eo_slice, _eo_div, ExactOddsError };\n"
)

# index.js
il = ["// exactodds — provably-fair casino rule packs. Same rules, every seat.",
      "// Generated — do not hand-edit.",
      "const SOURCE_HASHES = " + json.dumps(
          {s: json.load(open(os.path.join(ROOT, "receipts", s + ".receipt.json")))["source_hash"]
           for s in SLUGS}, indent=2) + ";",
      "",
      "const programs = {};"]
for slug, fns in index_entries:
    var = slug.replace("-", "_")
    il.append(f"programs['{slug}'] = require('./rules/{slug}');")
il += ["",
       "module.exports = {",
       "  programs,",
       "  SOURCE_HASHES,",
       "  version: require('./package.json').version,",
       "};",
       "// Flat access: every rule function is also exported by name."]
for slug, fns in index_entries:
    for fn in fns:
        il.append(f"module.exports['{fn}'] = programs['{slug}']['{fn}'];")
open(os.path.join(SDK, "index.js"), "w").write("\n".join(il) + "\n")

# test/run.js — replays audited say() calls, diffs golden fixtures
tl = ["// Replays every audited say() from the .exactodds sources against the built",
      "// modules and diffs the golden fixtures. Any drift fails loudly.",
      "const fs = require('fs');",
      "const path = require('path');",
      "const { programs } = require('../index.js');",
      "",
      "const cases = " + json.dumps(
          [{"slug": s, "says": says, "fixture": fix} for s, says, fix in test_cases],
          indent=2) + ";",
      "",
      "let failures = 0;",
      "for (const c of cases) {",
      "  const mod = programs[c.slug];",
      "  const fns = {};",
      "  for (const k of Object.keys(mod)) fns[k] = mod[k];",
      "  // evaluate each say(...) with rule fns in scope",
      "  const argNames = Object.keys(fns);",
      "  c.says.forEach((expr, i) => {",
      "    const fn = new Function(...argNames, 'return (' + expr + ');');",
      "    let got;",
      "    try { got = String(fn(...argNames.map(a => fns[a]))); }",
      "    catch (e) { got = 'THREW: ' + e.message; }",
      "    const want = c.fixture[i];",
      "    if (got !== want) { failures++;",
      '      console.error(`FAIL ${c.slug}#${i}: got ${got}, want ${want}`); }',
      "  });",
      "}",
      "const total = cases.reduce((n, c) => n + c.says.length, 0);",
      "if (failures) { console.error(`${failures}/${total} checks FAILED`); process.exit(1); }",
      "console.log(`all ${total} audited checks PASS`);"]
open(os.path.join(SDK, "test", "run.js"), "w").write("\n".join(tl) + "\n")

print(f"built {len(SLUGS)} rule modules, {len(all_funcs)} functions, "
      f"{sum(len(f) for _, f in index_entries)} flat exports")
